# Generated by Django 5.0.1 on 2024-01-30 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partediario',
            name='agenteDto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppParte.departamento'),
        ),
        migrations.AddField(
            model_name='partediario',
            name='agenteParte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppParte.agente'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='detalle',
            field=models.CharField(choices=[('P', 'Presente'), ('LAO', 'Licencia Anual Ordinaria'), ('LE', 'Licencia por Enfermedad'), ('LM', 'Licencia por Maternidad'), ('Art', 'Articulo'), ('A', 'Ausente')], default='Presente', max_length=35),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='usuarioVisado',
            field=models.CharField(max_length=4),
        ),
    ]
