# Generated by Django 5.0.1 on 2024-01-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0002_partediario_agentedto_partediario_agenteparte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='dto_agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppParte.departamento'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='usuarioVisado',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
