# Generated by Django 5.0.1 on 2024-01-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0003_agente_dto_agente_alter_partediario_usuariovisado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partediario',
            name='agenteDto',
        ),
    ]
