# Generated by Django 5.0.1 on 2024-02-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0004_remove_partediario_agentedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='partediario',
            name='cargaFecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
