# Generated by Django 5.0.1 on 2024-02-01 20:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0005_partediario_cargafecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partediario',
            name='usuarioVisado',
            field=models.CharField(max_length=4, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
