# Generated by Django 5.0.1 on 2024-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0006_alter_partediario_usuariovisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partediario',
            name='usuarioVisado',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
