# Generated by Django 5.0.1 on 2024-02-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0007_alter_partediario_usuariovisado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partediario',
            old_name='cargaFecha',
            new_name='FechaModificado',
        ),
        migrations.AddField(
            model_name='partediario',
            name='FechaParte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partediario',
            name='FechaVisado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partediario',
            name='usuarioModifica',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='usuarioVisado',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
