# Generated by Django 5.0.1 on 2024-02-05 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParte', '0008_rename_cargafecha_partediario_fechamodificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partediario',
            name='dto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppParte.departamento'),
        ),
    ]
